### ISSUE TITLE
Are you still looking for a new maintainer?

### ISSUE THREAD

**Issue by midoublelo** [Xtruct/Xtruct#7]
If you still need a new maintainer, I can take over from you if you would like.

**Comment by aolko** [comment]
Yes, i am.

**Comment by midoublelo** [comment]
How can I contact you so we can discuss this?

**Comment by aolko** [comment]
> How can I contact you so we can discuss this?

twitter or discord (preferable) in my profile

**Comment by midoublelo** [comment]
Added on discord
